name: Build, test and publish Storybook to GitHub Pages

on:
  push:
    branches:
      - 'main'
      - '**'
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

  test:
    timeout-minutes: 60
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run storybook tests
        run: npm run test

  deploy:
    if: always()
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: npm ci
          build_command: npm run build-storybook
          path: storybook-static
          checkout: false
